d1:
	pdflatex d1_25_shuttleql.tex && rm d1_25_shuttleql.aux d1_25_shuttleql.log

d2:
	pdflatex d2_25_shuttleql.tex && rm d2_25_shuttleql.aux d2_25_shuttleql.log

d3:
	pdflatex d3_25_shuttleql.tex && rm d3_25_shuttleql.aux d3_25_shuttleql.log

clean:
	rm *.pdf *.aux *.log
