d1:
	pdflatex d1_25_shuttleql-slides.tex && rm d1_25_shuttleql-slides.aux d1_25_shuttleql-slides.log d1_25_shuttleql-slides.nav d1_25_shuttleql-slides.out d1_25_shuttleql-slides.snm d1_25_shuttleql-slides.toc

d3:
	pdflatex d3_25_shuttleql-slides.tex && rm d3_25_shuttleql-slides.aux d3_25_shuttleql-slides.log d3_25_shuttleql-slides.nav d3_25_shuttleql-slides.out d3_25_shuttleql-slides.snm d3_25_shuttleql-slides.toc

clean:
	rm *.pdf *.aux *.log *.nav *.out *.snm *.toc
