all:
	pdflatex d1_25_shuttleql-slides.tex && rm d1_25_shuttleql-slides.aux d1_25_shuttleql-slides.log d1_25_shuttleql-slides.nav d1_25_shuttleql-slides.out d1_25_shuttleql-slides.snm d1_25_shuttleql-slides.toc
clean:
	rm d1_25_shuttleql-slides.pdf
